MAKE="make"
CLEAN="make clean"
PACKAGE_NAME="qapkyy_qy"
PACKAGE_VERSION="1.9"
BUILT_MODULE_NAME[0]="qapkyy_qy"
BUILT_MODULE_LOCATION[0]="src/"
DEST_MODULE_LOCATION[0]="/kernel/drivers/platform/x86"
AUTOINSTALL="yes"
